name: Push file to Cloudsmith repo

inputs:
  vendor:
    description:  OS vendor
    required: true
  codename:
    description:  OS distro codename
    required: true
  fileName:
    description:  Name of file to push
    required: true

runs:
  using: composite
  steps:
  - name: Push ${{ inputs.fileName }} to Cloudsmith
    uses: cloudsmith-io/action@master
    with:
      api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      command: "push"
      format: "deb"
      owner: ${{ vars.CLOUDSMITH_OWNER }}
      repo: ${{ vars.CLOUDSMITH_REPO }}
      distro: ${{ inputs.vendor }}
      release: ${{ inputs.codename }}
      republish: "true"
      file: ${{ inputs.fileName }}
