---
name: cloudsmith.io packages
on:
  - push
  - pull_request

jobs:
  setup:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read_vars.outputs.content }}
    steps:

      - name: Clone git repository
        uses: actions/checkout@v4

      - name: Read matrix
        id: read_vars
        uses: pixelfederation/gh-action-yaml-to-json@v0.2.0
        with:
          directory: .github
          file: debian-distro-settings.yaml

      - name:  Debug matrix
        run: |
          echo "matrix json string:"
          echo "${{ steps.read_vars.outputs.content }}"

  buildPackages:
    name: Build ${{ matrix.codename }} ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    needs:  setup
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}
    outputs:
      pkg_ver: ${{ steps.build_packages.outputs.pkg_ver }}
      matrix: ${{ needs.setup.outputs.matrix }}

    steps:

      - name: Clone git repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:${{ matrix.codename }}
          push: true
          build-args: |
            DEBIAN_DISTRO_BASE=${{ matrix.vendor }}:${{ matrix.codename }}
            ARCHITECTURE=${{ matrix.architecture }}
            ENTRYPOINT=/usr/bin/entrypoint
            DEBIAN_DIR=debian
          labels: |
            os_vendor=${{ matrix.vendor }}
            os_codename=${{ matrix.codename }}
            os_architecture=${{ matrix.architecture }}
          file: .github/Dockerfile
          cache-from: type=gha,scope=${{ matrix.codename }}
          cache-to: type=gha,mode=max,scope=${{ matrix.codename }}

      - name: Cache .ccache directory
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ matrix.codename }}-${{ matrix.architecture }}

      - name: Build packages
        id: build_packages
        shell: bash
        env:
          ARCHITECTURE: ${{ matrix.architecture }}
          DOCKER_TAG: ghcr.io/${{ github.repository }}:${{ matrix.codename }}
        run: |
          set -e

          echo ::group::Docker image pull
          docker pull $DOCKER_TAG
          echo ::endgroup::

          PKG_VER="$(dpkg-parsechangelog -S version | sed 's/^[0-9]*://')"
          echo "::set-output name=pkg_ver::$PKG_VER"
          echo "Package version:  $PKG_VER"
          PKG_VER_ARCH="${PKG_VER}_${ARCHITECTURE}"
          echo "::set-output name=pkg_ver_arch::$PKG_VER_ARCH"
          echo "pkg_ver_arch:  $PKG_VER_ARCH"

          docker run \
              -v ${HOME}:${HOME} \
              -e UID_OUT=$(id -u) -e GID_OUT=$(id -g) \
              -e HOME=${HOME} \
              -e PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
              -e CCACHE_DIR=${PWD}/.ccache \
              -w ${PWD} \
              $DOCKER_TAG \
              dpkg-buildpackage -uc -us -a${ARCHITECTURE}


          echo ::group::Shuffle artifacts
          mkdir -p pkgs
          ls -l ..
          mv ../linuxcnc-ethercat*${PKG_VER}* pkgs/
          echo "Final packages for upload:"
          ls -l pkgs/
          echo ::endgroup::

      - name: >
          Artifacts ${{ matrix.codename}} ${{ matrix.architecture }}
        uses: actions/upload-artifact@v4
        env:
          NAME_BASE: ${{ matrix.codename }}-${{ env.PKG_VER_ARCH }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPO: ${{ github.event.repository.name }}
        with:
          name: pkgs_${{ matrix.codename }}-${{ matrix.architecture }}
          path: pkgs
          if-no-files-found: error

  pushPackages:
    needs: buildPackages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.buildPackages.outputs.matrix) }}
    name: Push pkgs ${{ matrix.codename }} ${{ matrix.architecture }}
    env:
      VERSION: ${{ needs.buildPackages.outputs.pkg_ver }}
      VERSION_ARCH: >-
        ${{ needs.buildPackages.outputs.pkg_ver }}_${{ matrix.architecture }}
      CLOUDSMITH_VARS: |
        {
          "api_key" : "${{ secrets.CLOUDSMITH_API_KEY }}",
          "owner" : "${{ vars.CLOUDSMITH_OWNER }}",
          "repo": "${{ vars.CLOUDSMITH_REPO }}",
          "vendor": "${{ matrix.vendor }}",
          "codename": "${{ matrix.codename }}"
        }

    steps:

      - name: Clone git repository
        uses: actions/checkout@v4

      - name: Download pkg build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pkgs_${{ matrix.codename }}-${{ matrix.architecture }}
          path: .

      - name: Debug artifacts
        run: |
          ls -la

      - name:  Push main package
        uses: ./.github/actions/pushToCloudsmith
        with:
          vars: ${{ env.CLOUDSMITH_VARS }}
          fileName: linuxcnc-ethercat_${{ env.VERSION_ARCH }}.deb

      - name:  Push debug pkg
        uses: ./.github/actions/pushToCloudsmith
        with:
          vars: ${{ env.CLOUDSMITH_VARS }}
          fileName: linuxcnc-ethercat-dbgsym_${{ env.VERSION_ARCH }}.ddeb

      - name:  Push source file
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          WHERE=${{ vars.CLOUDSMITH_OWNER }}/${{ vars.CLOUDSMITH_REPO }}
          WHERE+=/${{ matrix.vendor }}/${{ matrix.codename }}
          bin/cloudsmith push deb \
              $WHERE \
              linuxcnc-ethercat_${{ env.VERSION_ARCH }}.deb \
              --sources-file linuxcnc-ethercat_${{ env.VERSION }}.tar.xz \
              --republish
